# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: article
  hint: true
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true

- name: farm_info
  unique: true
  contents:
  - name: farm_name
    type: EssenceText
    hint: true
  - name: description
    type: EssenceRichtext
    hint: true
  - name: picture
    type: EssencePicture
    hint: true

- name: product
  contents:
  - name: product_name
    type: EssenceZack
    hint: true
  - name: variety
    type: EssenceText
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: organic
    type: EssenceBoolean
    hint: true

